server:
  port: 9009
spring:
  application:
    name: tensquare-sms #指定服务名
  rabbitmq:
    host: 192.168.25.128
aliyun:
  sms:
   accessKeyId: LTAIE2pI2JwQEtIv
   accessKeySecret: 8aCxierbbvNPbM0bjNULzQ6v7cauyv
   template_code: SMS_164435006
   sign_name: 品优购
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8686/eureka/eureka
  instance:
    prefer-ip-address: true