spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/batch?createDatabaseIfNotExist=true&characterEncoding=UTF8
    username: root
    password: root

  batch:
    initialize-schema: always
student:
  path: E:\batch
url:
  lxgm: \lxgm\