server:
  port: 9006
spring:
  application:
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 192.168.25.128
      database: spitdb

  redis:
    host: 192.168.25.128
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8686/eureka/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: itcast